import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body className="flex bg-gray-50 min-h-screen text-gray-800">
        <Sidebar />
        <main className="flex-1 px-10 py-8">{children}</main>
      </body>
    </html>
  );
}
